[unstable]
build-std = [ "core", "compiler_builtins" ]
build-std-features = [ "compiler-builtins-mem" ]

[build]
target = "stage2/i686-stage2.json"
dep-info-basedir = "."

[target.i686-stage2]
runner = [ "./run-cargo.sh", "10", "-device isa-debug-exit,iobase=0xf4,iosize=0x04 -serial stdio" ]
